Code/EC-TH2012-J/Models/Donhang/ChitietdonhangModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EC_TH2012_J.Models
{
    public class ChitietdonhangModel
    {
        public string MaDH { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public SanPham SanPham { get; set; }

        public List<ChitietdonhangModel>getChiTietDonHang(string maDH)
        {
            using(Entities db = new Entities())
            {
                List<ChitietdonhangModel> danhSachChiTiet = new List<ChitietdonhangModel>();
                var ds = (from p in db.ChiTietDonHangs where p.MaDH == maDH select p).ToList();
                foreach(var temp in ds)
                {
                    
                    ChitietdonhangModel tam = new ChitietdonhangModel()
                    {
                        MaDH = temp.MaDH,
                        SoLuong = temp.SoLuong,
                        ThanhTien = temp.ThanhTien,
                        SanPham = temp.SanPham
                    };
                    string tt = temp.SanPham.GiaTien.ToString();
                    danhSachChiTiet.Add(tam);
                }
                return danhSachChiTiet;
            }
        }
    }
}

Code/EC-TH2012-J/Models/Donhang/DonhangKHModel.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;

namespace EC_TH2012_J.Models
{
    public class DonhangKHModel
    {
        public DonHangKH donHang;
        public AspNetUser nguoiMua;
        public String nguoiNhan;
        public String tinhTrangDH;
        public List<DonhangKHModel> Xemdonhang(string makh)
        {
            using (Entities db = new Entities())
            {
                List<DonhangKHModel> listDh = new List<DonhangKHModel>();
                db.DonHangKHs.AsNoTracking();
                var danhsach = from p in db.DonHangKHs where p.MaKH == makh select p;
                foreach (var temp in danhsach.ToList())
                {
                    AspNetUser users = (from p in db.AspNetUsers where p.Id == makh select p).FirstOrDefault();

                    listDh.Add(new DonhangKHModel()
                    {
                        donHang = temp,
                        nguoiMua = users,
                        tinhTrangDH = gettinhTrangDH(temp.TinhTrangDH)
                    });
                }
                return listDh;
            }
        }

        private string gettinhTrangDH(int? nullable)
        {
            switch (nullable)
            {
                case 0:
                    {
                        return "Chưa giao";
                    }
                case 1:
                    {
                        return "Đang duyệt";
                    }
                case 2:
                    {
                        return "Đang giao hàng";
                    }
                case 3:
                    {
                        return "Đã giao";
                    }
                case 4:
                    {
                        return "Đã hủy";
                    }
            }
            return "Đang duyệt";
        }
        public bool HuyDH(string maDH)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    string query = "update DonHangKH set TinhTrangDH = '4' where MaDH ='" + maDH + "'";
                    db.Database.ExecuteSqlCommand(query);
                    return true;
                }
            }
            catch (Exception e)
            {
                return false;
            }
        }

        public AspNetUser Xemttnguoidung(string id)
        {
            using (Entities db = new Entities())
            {
                AspNetUser users = (from p in db.AspNetUsers where p.Id == id select p).FirstOrDefault();
                return users;
            }
        }
        public void Luudonhang(Donhangtongquan a, string maKH, Giohang giohang)
        {
            try
            {
                using (Entities db = new Entities())
                {
                    DonHangKH dhkh = new DonHangKH();
                    dhkh.MaDH = RandomMa();
                    dhkh.MaKH = maKH;

                    dhkh.Diachi = a.address;
                    dhkh.Dienthoai = a.phoneNumber;
                    dhkh.Ghichu = a.Note;
                    dhkh.NgayDatMua = DateTime.Now;
                    dhkh.TinhTrangDH = 1;
                    dhkh.Tongtien = giohang.TinhtongtienCart();
                    dhkh.PhiVanChuyen = 0;

                    dhkh = db.DonHangKHs.Add(dhkh);
                    db.SaveChanges();

                    Luuchitietdonhang(giohang, db, dhkh.MaDH);
                }
            }
            catch (Exception e) { }
        }

        private void Luuchitietdonhang(Giohang giohang, Entities db, string maDH)
        {
            foreach (var temp in giohang.getGiohang())
            {
                ChiTietDonHang chiTiet = new ChiTietDonHang()
                {
                    MaDH = maDH,
                    MaSP = temp.sanPham.MaSP,
                    SoLuong = temp.Soluong,
                    ThanhTien = (decimal)temp.Thanhtien
                };
                db.ChiTietDonHangs.Add(chiTiet);

            }
            db.SaveChanges();
        }
        public string RandomMa()
        {
            string maID;
            Random rand = new Random();
            do
            {
                maID = "";
                for (int i = 0; i < 5; i++)
                {
                    maID += rand.Next(9);
                }
            }
            while (!KiemtraID(maID));
            return maID;
        }

        private bool KiemtraID(string maID)
        {
            using (Entities db = new Entities())
            {
                var temp = db.DonHangKHs.Find(maID);
                if (temp == null)
                    return true;
                return false;
            }
        }

        internal IQueryable<DonHangKH> TimDonHang(string key, string mobile, DateTime? date, int? status)
        {
            Entities db = new Entities();

            IQueryable<DonHangKH> lst = db.DonHangKHs;
            if (!string.IsNullOrEmpty(key))
                lst = lst.Where(m => m.MaDH.Contains(key));
            if (!string.IsNullOrEmpty(mobile))
                lst = lst.Where(m => m.Dienthoai.Contains(mobile));
            if (status != null)
                lst = lst.Where(m => m.TinhTrangDH == status);
            if (date != null)
                lst = lst.Where(m => m.NgayDatMua.Value.Year == date.Value.Year && m.NgayDatMua.Value.Month == date.Value.Month && m.NgayDatMua.Value.Day == date.Value.Day);
            return lst;

        }

        internal bool UpdateTinhTrang(string madh, int? tt)
        {
            if (tt == null) return false;
            try
            {
                Entities db = new Entities();
                DonHangKH dh = db.DonHangKHs.Find(madh);
                if (dh.TinhTrangDH == 4 || dh.TinhTrangDH == 3)
                    return false;
                if (dh.TinhTrangDH == 1)
                    if (tt == 2 || tt == 3)
                    {
                        foreach (var item in dh.ChiTietDonHangs)
                        {
                            SanPhamModel spm = new SanPhamModel();
                            spm.UpdateSL(item.MaSP, item.SoLuong, false);
                        }
                    }
                if (dh.TinhTrangDH == 2)
                {
                    if (tt == 4)
                    {
                        foreach (var item in dh.ChiTietDonHangs)
                        {
                            SanPhamModel spm = new SanPhamModel();
                            spm.UpdateSL(item.MaSP, item.SoLuong, true);
                        }
                    }
                    if (tt == 1) return false;
                }
                string query = "update DonHangKH set TinhTrangDH = " + tt + " where MaDH ='" + madh + "'";
                db.Database.ExecuteSqlCommand(query);
                return true;

            }
            catch (Exception e)
            {
                return false;
            }
        }

        internal IQueryable<ChiTietDonHang> ChiTietDonHang(string maDH)
        {
            Entities db = new Entities();
            return db.ChiTietDonHangs.Where(m => m.MaDH.Contains(maDH));
        }

        internal IQueryable<object> ThongKeDoanhThu(DateTime? froms, DateTime? tos)
        {           
            Entities db = new Entities();
            var s = from p in db.DonHangKHs
                    where p.TinhTrangDH == 3 && p.NgayDatMua >= froms && p.NgayDatMua <= tos
                    group p by EntityFunctions.TruncateTime(p.NgayDatMua) into gro
                    select new { ngaymua = gro.Key.Value, tongtien = gro.Sum(r => r.Tongtien) };
            return s;
        }


        internal IQueryable<object> ThongKeTiTrong(DateTime? froms, DateTime? tos)
        {
            Entities db = new Entities();
            var s = from p in db.ChiTietDonHangs
                    where p.DonHangKH.TinhTrangDH == 3 && p.DonHangKH.NgayDatMua >= froms && p.DonHangKH.NgayDatMua <= tos
                    group p by p.SanPham.TenSP into gro
                    select new { TenSP = gro.Key, SL = gro.Sum(r => r.SoLuong) };
            return s;
        }
    }
}

Code/EC-TH2012-J/Models/Donhang/Donhangtongquan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EC_TH2012_J.Models
{
    public class Donhangtongquan
    {
        public string address { get; set; }
        [Required(ErrorMessage = "Vui lòng cung cấp số điện thoại", AllowEmptyStrings = false)]
        [RegularExpression(@"(09)\d{8}|(01)\d{9}", ErrorMessage = "Entered phone format is not valid.")]
        [Display(Name = "Điện thoại liên lạc")]
        [DataType(DataType.PhoneNumber)]
        public string phoneNumber { get; set; }
        public string buyer { get; set; }
        public string seller { get; set; }
        public string Note { get; set; }
    }
}

Code/EC-TH2012-J/Controllers/DonhangController.cs
using EC_TH2012_J.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace EC_TH2012_J.Controllers
{
    [AuthLog(Roles = "Quản trị viên,Nhân viên")]
    public class DonhangController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TimDonHang(string key, string mobile, DateTime? date, int? status, int? page)
        {
            DonhangKHModel spm = new DonhangKHModel();
            ViewBag.key = key;
            ViewBag.date = date;
            ViewBag.status = status;
            ViewBag.mobile = mobile;
            return PhanTrangDH(spm.TimDonHang(key, mobile, date, status), page, null);
        }

        [HttpPost]
        public ActionResult UpdateTinhTrangDH(string madh, int? tt)
        {
            DonhangKHModel dh = new DonhangKHModel();
            dh.UpdateTinhTrang(madh, tt);
            return RedirectToAction("TimDonHang");
        }

        [HttpPost]
        public ActionResult MultibleUpdate(List<string> lst, int? tt)
        {
            foreach (var item in lst)
            {
                UpdateTinhTrangDH(item, tt);
            }
            return RedirectToAction("TimDonHang");
        }

        public ActionResult PhanTrangDH(IQueryable<DonHangKH> lst, int? page, int? pagesize)
        {
            int pageSize = (pagesize ?? 10);
            int pageNumber = (page ?? 1);
            return PartialView("DonHangPartial", lst.OrderBy(m => m.TinhTrangDH).ToPagedList(pageNumber, pageSize));
        }

        // GET: Donhang
        public ActionResult Chitietdonhang(string id)
        {
            DonhangKHModel ctdh = new DonhangKHModel();
            return PartialView("DonHangDetail",ctdh.ChiTietDonHang(id));
        }
    }
}

Code/EC-TH2012-J/Views/Donhang/DonHangDetail.cshtml
@model IQueryable<EC_TH2012_J.Models.ChiTietDonHang>

<div class="modal fade in" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: block;">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" onclick="closeDialog();">×</button>
                <h3> Chi tiết đơn hàng #@Model.First().MaDH </h3>
            </div>
            <div class="modal-body">
                <table class="table-hover table-bordered">
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.First().SanPham.TenSP)</th>
                        <th>@Html.DisplayNameFor(model => model.First().SoLuong)</th>
                        <th>@Html.DisplayNameFor(model => model.First().ThanhTien)</th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.SanPham.TenSP</td>
                            <td>@item.SoLuong</td>
                            <td>@string.Format("{0:0,0}", @item.ThanhTien) </td>
                        </tr>
                    }
                </table>
            </div>
            @*<div class="modal-footer">
                    <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
                    <a href="#" class="btn btn-primary" data-dismiss="modal">Save changes</a>
                </div>*@
        </div>
    </div>
</div>

Code/EC-TH2012-J/Views/Donhang/DonHangPartial.cshtml
@using EC_TH2012_J.Models;
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<DonHangKH>


<table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
    <thead>
        <tr>
            <th>
                <input type="checkbox" onclick="toggle(this)" />
            </th>
            <th>Mã đơn hàng</th>
            <th>Người mua</th>
            <th>Tổng</th>
            <th>Ngày mua</th>
            <th>Trạng thái</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr onclick="ChiTietItem('@Url.Action("Chitietdonhang","Donhang")','@item.MaDH')">
                <td rowspan="3">
                    <input type="checkbox" name="lstdel" value="@item.MaDH" />
                </td>
                <td class="center" rowspan="3">@item.MaDH</td>
                <td class="center">
                    <span style="font-weight:600; color:#ff0000"> Họ tên:</span><span> @item.AspNetUser.HoTen</span>
                </td>
                <td class="center" rowspan="3"> @string.Format("{0:0,0}", @item.Tongtien) VNĐ</td>
                <td class="center" rowspan="3">@item.NgayDatMua</td>
                <td class="center" rowspan="3">
                    @if (item.TinhTrangDH == 1)
                    { <span class="label" style="background-color:#808080;">Đang duyệt</span> }
                    else if (item.TinhTrangDH == 2)
                    { <span class="label label-info">Đang giao</span> }
                    else if (item.TinhTrangDH == 3)
                    { <span class="label label-success">Đã giao</span> }
                    else
                    {<span class="label label-danger">Hủy</span>}
                </td>
            </tr>
            <tr><td class="center"><span style="font-weight:600; color:#ff0000"> Điện thoại:</span> @item.Dienthoai</td></tr>
            <tr><td class="center"><span style="font-weight:600; color:#ff0000"> Địa chỉ:</span> @item.Diachi</td></tr>
        }
    </tbody>
</table>

<div class="pagination-holder">
    <div class="row">
        <div class="col-xs-12 col-sm-6 text-left">
            <div id="nav_grid">
                @Html.PagedListPager(Model, page => Url.Action("TimDonHang", "Donhang", new { key = @ViewBag.key, date = @ViewBag.date, status = @ViewBag.status, mobile = @ViewBag.mobile, page = page }))
            </div>
        </div>
        <div class="col-xs-12 col-sm-6">
            <div class="result-counter">
                Có tât cả <span>@Model.TotalItemCount</span> dòng
            </div>
        </div>
    </div><!-- /.row -->
</div><!-- /.pagination-holder -->

<div id="show-dialog-detail" style="display:none">
</div>

Code/EC-TH2012-J/Views/Donhang/Index.cshtml
@{
    ViewBag.Title = "Quản lý đơn hàng của khách";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2><i class="glyphicon glyphicon-user"></i>@ViewBag.Title</h2>
                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round btn-default">
                        <i class="glyphicon glyphicon-chevron-up"></i>
                    </a>
                    <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <div class="alert alert-info" id="alert-info" style="display:none"></div>
                <div class="form-inline" style="text-align: right; padding: 10px">
                    <div class="input-group">
                        @Html.DropDownList("value", new SelectList(new List<object>
                        {
                            new { value = "1" , text = "Dang duyệt"  },
                            new { value = "2" , text = "Đang giao" },
                            new { value = "3" , text = "Đã giao" },
                            new { value = "4" , text = "Hủy" },
                        }, "value", "text"), "--Trạng thái--", new { @class = "form-control", id = "trangthai", onchange = "timkiemdh()" })
                    </div>

                    <div class="input-group">
                        <span class="input-group-addon"><i class="red">Ngày</i></span>
                        <input id="dhday" type="date" class="form-control" onchange="timkiemdh()">
                    </div>

                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-search red"></i></span>
                        <input id="mobile" type="text" class="form-control" placeholder="Số điện thoại" oninput="timkiemdh()">
                    </div>

                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-search red"></i></span>
                        <input id="madh" type="text" class="form-control" placeholder="Mã đơn hàng" oninput="timkiemdh()">
                    </div>
                    

                </div>
                <div class="form-inline" style="text-align: right; padding: 10px">
                    <div class="input-group">
                        @Html.DropDownList("SetStatus", new SelectList(new List<object>
                        {
                            new { value = "1" , text = "Dang duyệt"  },
                            new { value = "2" , text = "Đang giao" },
                            new { value = "3" , text = "Đã giao" },
                            new { value = "4" , text = "Hủy" },
                        }, "value", "text"), "--- Sửa trạng thái đơn hàng ---", new { @class = "form-control", id = "setstatus" })
                        <span class="input-group-addon" onclick="SetStatus('@Url.Action("MultibleUpdate", "Donhang")')" style="cursor:pointer"><i class="glyphicon glyphicon glyphicon-wrench blue"></i></span>
                    </div>
                </div>

                <div class="Ajax-Table" id="Ajax-Table">
                    @Html.Action("TimDonHang", "Donhang")
                </div>

            </div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->